# serverless.yml

myNextApplication:
  component: "@sls-next/serverless-component@3.1.0-alpha.3"
  inputs:
    bucketName: test-bucketname
    bucketRegion: ap-northeast-2
    region: ap-northeast-2
    runtime: nodejs14.x
    enableS3Acceleration: false
